name: tweet_sentiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - scikit-learn
  - ipykernel
  - pip:
    - tensorflow
    - nlp
    - datasets